version: '3.8'

services:
  frontend:
    build:
      context: ./frontAnfitrioes
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Api/database:/app/database
    environment:
      FLASK_ENV: development
